DROP TABLE IF EXISTS Person;

CREATE TABLE Person (
  id INT NOT NULL AUTO_INCREMENT,
  firstname VARCHAR(35) NOT NULL,
  lastname VARCHAR(35) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,

  PRIMARY KEY(id)
);
